<table class="table table-striped">
    <thead>
        <th>ID</th>
        <th>Name</th>
        <th>Gender</th>
        <th>Email</th>
        <th>Mobile Number</th>
        <th>Date of Birth</th>
        <th>Designation</th>
        <th>Branch</th>
        <th>Actions</th>
    </thead>
    <tbody>
        <?php if ($this->paginator && count($this->paginator) > 0): ?>
            <?php foreach ($this->paginator as $user): ?>
            <tr>
                <td><?php echo $user['id']; ?></td>
                <td><?php echo $user['name']; ?></td>
                <td><?php echo $user['gender']; ?></td>
                <td><?php echo $user['email']; ?></td>
                <td><?php echo $user['mobile_number']; ?></td>
                <td><?php echo $user['date_of_birth']; ?></td>
                <td><?php echo $user['designation']; ?></td>
                <td><?php echo $user['branch']; ?></td>
                <td>
                    <a href="<?php echo $this->url([
                        'controller' => 'user',
                        'action' => 'edit',
                        'id' => $user['id']
                    ], 'default', true) ?>">Edit</a>
                    <a href="<?php echo $this->url([
                        'controller' => 'user',
                        'action' => 'delete',
                        'id' => $user['id']
                    ], 'default', true) ?>">Delete</a>
                </td>
            </tr>
            <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td colspan="9" align="center">No records found.</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>